########################################################################################################################
#
# ░█████╗░██╗░░░██╗████████╗░█████╗░  ███╗░░░███╗███████╗░██████╗░██████╗░█████╗░░██████╗░███████╗
# ██╔══██╗██║░░░██║╚══██╔══╝██╔══██╗  ████╗░████║██╔════╝██╔════╝██╔════╝██╔══██╗██╔════╝░██╔════╝
# ███████║██║░░░██║░░░██║░░░██║░░██║  ██╔████╔██║█████╗░░╚█████╗░╚█████╗░███████║██║░░██╗░█████╗░░
# ██╔══██║██║░░░██║░░░██║░░░██║░░██║  ██║╚██╔╝██║██╔══╝░░░╚═══██╗░╚═══██╗██╔══██║██║░░╚██╗██╔══╝░░
# ██║░░██║╚██████╔╝░░░██║░░░╚█████╔╝  ██║░╚═╝░██║███████╗██████╔╝██████╔╝██║░░██║╚██████╔╝███████╗
# ╚═╝░░╚═╝░╚═════╝░░░░╚═╝░░░░╚════╝░  ╚═╝░░░░░╚═╝╚══════╝╚═════╝░╚═════╝░╚═╝░░╚═╝░╚═════╝░╚══════╝
#
# Documentation: https://zessentials.groupez.dev/
#
########################################################################################################################

enable: true

# Interval between messages in seconds
interval: 300

# If true, messages will be sent in random order. If false, they will be sent sequentially.
random-order: false

# List of messages to broadcast
messages:
  - lines:
      - ""
      - "#ffd353ℹ ᴀɴɴᴏᴜɴᴄᴇᴍᴇɴᴛ"
      - "&7Welcome to our server! Type &f/rules &7for server rules."
      - ""
  - lines:
      - ""
      - "#ffd353ℹ ᴀɴɴᴏᴜɴᴄᴇᴍᴇɴᴛ"
      - "&7Join our Discord: &f/discord"
      - ""
