########################################################################################################################
#
# ██████╗░██╗░░░██╗██╗░░░░░███████╗░██████╗
# ██╔══██╗██║░░░██║██║░░░░░██╔════╝██╔════╝
# ██████╔╝██║░░░██║██║░░░░░█████╗░░╚█████╗░
# ██╔══██╗██║░░░██║██║░░░░░██╔══╝░░░╚═══██╗
# ██║░░██║╚██████╔╝███████╗███████╗██████╔╝
# ╚═╝░░╚═╝░╚═════╝░╚══════╝╚══════╝╚═════╝░
#
# Documentation: https://zessentials.groupez.dev/modules/rules
#
########################################################################################################################

enable: true

# Defines how to display server rules
# INVENTORY
# MESSAGE
rule-type: INVENTORY
