########################################################################################################################
#
#  ░██╗░░░░░░░██╗░█████╗░██████╗░██████╗░
#  ░██║░░██╗░░██║██╔══██╗██╔══██╗██╔══██╗
#  ░╚██╗████╗██╔╝███████║██████╔╝██████╔╝
#  ░░████╔═████║░██╔══██║██╔══██╗██╔═══╝░
#  ░░╚██╔╝░╚██╔╝░██║░░██║██║░░██║██║░░░░░
#  ░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░░░░
#
# Documentation: https://zessentials.groupez.dev/modules/warp
#
########################################################################################################################

enable: true

# Opens the warps menu. The file is warps.yml, you need to modify it to match your server
enable-inventory: false

# Send a message with the list of warps
enable-no-argument-message: true

