########################################################################################################################
#
# ░██████╗██████╗░░█████╗░░██╗░░░░░░░██╗███╗░░██╗
# ██╔════╝██╔══██╗██╔══██╗░██║░░██╗░░██║████╗░██║
# ╚█████╗░██████╔╝███████║░╚██╗████╗██╔╝██╔██╗██║
# ░╚═══██╗██╔═══╝░██╔══██║░░████╔═████║░██║╚████║
# ██████╔╝██║░░░░░██║░░██║░░╚██╔╝░╚██╔╝░██║░╚███║
# ╚═════╝░╚═╝░░░░░╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚═╝░░╚══╝
#
# Documentation: https://zessentials.groupez.dev/modules/spawn
#
########################################################################################################################

enable: true

# What priority should we use for handling respawns?
# Set this to none, if you want vanilla respawning behaviour.
# Set this to lowest, if you want Multiverse to handle the respawning.
# Set this to high, if you want EssentialsSpawn to handle the respawning.
# Set this to highest, if you want to force EssentialsSpawn to handle the respawning.
# Note: Changes will not apply until after the server is restarted.
respawn-listener-priority: highest

# What priority should we use for handling spawning on joining the server?
# See respawn-listener-priority for possible values.
# Note: Changing this may impact or break spawn-on-join functionality.
# Note: Changes will not apply until after the server is restarted.
spawn-join-listener-priority: highest

# When the player dies, does he have to respawn to the respawn anchor
respawn-at-anchor: false

# When users die, should they respawn at their first home, instead of the spawnpoint?
respawn-at-home: false

# When users die, should they respawn at their bed instead of the spawnpoint?
respawn-at-bed: true
