########################################################################################################################
#
# ███████╗░█████╗░░█████╗░███╗░░██╗░█████╗░███╗░░░███╗██╗░░░██╗
# ██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗████╗░████║╚██╗░██╔╝
# █████╗░░██║░░╚═╝██║░░██║██╔██╗██║██║░░██║██╔████╔██║░╚████╔╝░
# ██╔══╝░░██║░░██╗██║░░██║██║╚████║██║░░██║██║╚██╔╝██║░░╚██╔╝░░
# ███████╗╚█████╔╝╚█████╔╝██║░╚███║╚█████╔╝██║░╚═╝░██║░░░██║░░░
# ╚══════╝░╚════╝░░╚════╝░╚═╝░░╚══╝░╚════╝░╚═╝░░░░░╚═╝░░░╚═╝░░░
#
# Documentation: https://zessentials.groupez.dev/modules/economy
#
########################################################################################################################

enable: true

# The economy that will be used by default.
default-economy: "money"

# List of available economies
economies:
  # Economy name
  - name: money
    # Economy display name. This name will be used to be displayed in player messages whenever possible.
    display-name: Money
    # Economy symbol
    symbol: "$"
    # Economy format
    format: "%price%$"
    # Should the economy be used for vault. Only one economy can work with vault.
    vault: true
    # The minimum number possible with this economy.
    min: -99999999999999999999999999999999999999999999999999999999999999
    # The maximum number possible with this economy.
    max: 99999999999999999999999999999999999999999999999999999999999999
    # The minimum number for /pay command
    min-pay: 0.1
    # The maximum number for /pay command
    max-pay: 999999999999999
    # Enable the ability to use /pay command with this economy
    enable-pay: true
    # Activate confirmation menu for /pay command. This menu will confirm that you really want to send money to the player
    enable-confirm-inventory: true
    # The minimum number to display the confirmation inventory, below the command will run directly
    min-confirm-inventory: 10000000
    # The format type of for numbers
    price-format: PRICE_WITH_REDUCTION

    # Economy name
  - name: coins
    # Economy display name. This name will be used to be displayed in player messages whenever possible.
    display-name: Coins
    # Economy symbol
    symbol: "⛁"
    # Economy format
    format: "%price%⛁"
    # Should the economy be used for vault. Only one economy can work with vault.
    vault: false
    # The minimum number possible with this economy.
    min: 0
    # The maximum number possible with this economy.
    max: 9999999999999999999999999
    # The minimum number for /pay command
    min-pay: 0.1
    # The maximum number for /pay command
    max-pay: 1000
    # Enable the ability to use /pay command with this economy
    enable-pay: true
    # Activate a confirmation menu for /pay command. This menu will confirm that you really want to send money to the player
    enable-confirm-inventory: true
    # The minimum number to display the confirmation inventory, below the command will run directly
    min-confirm-inventory: 0
    # The format type of for numbers
    price-format: PRICE_RAW

# Set a number to use a format. For example, /pay Maxlego08 10k will become/pay Maxlego08 10000
# Allows to multiply a number very simply
number-format-sell-multiplication:
  - format: k
    multiplication: 1000
  - format: m
    multiplication: 1000000
  - format: b
    multiplication: 1000000000
  - format: t
    multiplication: 1000000000000
  - format: q
    multiplication: 1000000000000000
  - format: qq
    multiplication: 1000000000000000000
  - format: s
    multiplication: 1000000000000000000000
  - format: ss
    multiplication: 1000000000000000000000000
  - format: o
    multiplication: 1000000000000000000000000000
  - format: n
    multiplication: 1000000000000000000000000000000
  - format: d
    multiplication: 1000000000000000000000000000000000
  - format: uu
    multiplication: 1000000000000000000000000000000000000
  - format: dd
    multiplication: 1000000000000000000000000000000000000000
  - format: tr
    multiplication: 1000000000000000000000000000000000000000000

# Price format available
# - PRICE_RAW - Display the number without any changes
# - PRICE_WITH_DECIMAL_FORMAT - Display the number with the price-decimal-format configuration
# - PRICE_WITH_REDUCTION - Display the number with the price-reduction configuration
price-format: PRICE_WITH_REDUCTION

price-decimal-format: '#,###.#'

# Documentation for String format: https://www.geeksforgeeks.org/java-string-format-method-with-examples/
price-reductions:
  - format: "#.#" # Blank format to display text directly
    maxAmount: 1000
    # Add colors to text display, works with MiniMessage
    display: "#2bd66f%amount%"
  - format: "%.1fK"
    maxAmount: 1000000
    display: "#a3d14d%amount%"
  - format: "%.1fM"
    maxAmount: 1000000000
    display: "#ebbc23%amount%"
  - format: "%.1fB"
    maxAmount: 1000000000000
    display: "#eb4b23%amount%"
  - format: "%.2fT"
    maxAmount: 1000000000000000
    display: "#ff9999%amount%"
  - format: "%.2fQ"
    maxAmount: 100000000000000000
    display: "#ff3535%amount%"

# Baltop

# Enable or disable baltop
enable-baltop: true

# Time in seconds for baltop to update
baltop-refresh-seconds: 900

# Default value if a player does not exist for a position
baltop-placeholder-user-empty: "?"

# How to display baltop with/baltop command
# MESSAGE - Send a message
# INVENTORY - Open an inventory
baltop-display: MESSAGE

# Economy used to be displayed in baltop
baltop-message-economy: money

# Number of players to display in the message
baltop-message-amount: 10

# Allows players to cache their money offline.
# If you want to have a baltop system with all your players you must activate this option
store-offline-player-money: false

# Allows setting the default number and by economy that the player will receive when he first login.
default-economies:
  - economy: money
    amount: 100

pay-withdraw-reason: "Payment sent to %player%"
pay-deposit-reason: "Payment received from %player%"