########################################################################################################################
#
# ██╗████████╗███████╗███╗░░░███╗░██████╗
# ██║╚══██╔══╝██╔════╝████╗░████║██╔════╝
# ██║░░░██║░░░█████╗░░██╔████╔██║╚█████╗░
# ██║░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗
# ██║░░░██║░░░███████╗██║░╚═╝░██║██████╔╝
# ╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░
#
# Documentation: https://zessentials.groupez.dev/modules/items
# zMenu Items documentation: https://docs.zmenu.dev/configurations/items
#
########################################################################################################################

custom-items:
  master_sword:
    name: "<gradient:#e88d1e:#e8511e>ᴍᴀsᴛᴇʀ sᴡᴏʀᴅ</gradient>"
    material: DIAMOND_SWORD
    enchants:
      - SHARPNESS,10
      - UNBREAKING,10
      - LOOTING,10
      - MENDING,1